

// const BASE_URL = "http://localhost:5000/api/"
const BASE_URL = "http://13.233.96.169:8080/api/"
const BASE_URL = "http://localhost:8080/api/"


const CREATE_ADMIN_USER = BASE_URL + "create-admin-user"
const ADMIN_USER_LOGIN = BASE_URL + 'login-admin?'
const USERNAME = ""
const USER_BY_ID = BASE_URL + "get-user-byID"
const GET_ALL_ADMIN_USERS = BASE_URL + "admin-users/"
const UPDATE_ADMIN_USER = BASE_URL + "update-admin-user"
const DELETE_ADMIN_USER = BASE_URL + "delete-admin-user"

const GET_ALL_VIDEO_CATEGORY = BASE_URL  + "video-category/all-category"
const ADD_VIDEO_CATEGORY = BASE_URL + "video-category/create-category"
const DELETE_VIDEO_CATEGORY = BASE_URL + "video-category/delete-category"
const UPDATE_VIDEO_CATEGORY = BASE_URL + "video-category/update-category"

const GET_ALL_VIDEOS_BY_ADMIN = BASE_URL + "admin-videos"
const UPLOAD_VIDEO = BASE_URL + "upload-video"
const DELETE_VIDEO = BASE_URL + "videos/delete-video"

const ACTIVE_VIDEOS = BASE_URL + "inactive-video/"

// WallPaper
const UPLOAD_WALLPAPER = BASE_URL + "add-wallpaper"
const GET_ALL_WALLPAPER = BASE_URL + "get-wallpapers"
const ACTIVE_WALLPAPER = BASE_URL + "active-wallpaper/"

const FETCH_VERIFY_VIDEOS = BASE_URL + "admin-videos/verify-videos"

// verification process failed 
const UNVERIFY_VIDEO = BASE_URL + "admin-videos/make-verification-failed"
const REJECT_PUBLISH_VIDEO = BASE_URL + "admin-videos/make-unpublish-video"
const FETCH_VERIFICATION_FAILED = BASE_URL + "fetch-verification-failed-videos"


// video full details
const FETCH_PUBLISH_VIDEO_DETAILS = BASE_URL + "details/publish-video-details"
const FETCH_VIDEO_BY_ADMIN_DETAILS = BASE_URL + "details/video-by-admin-details"
const FETCH_VERIFY_VIDEO_DETAILS = BASE_URL + "details/verify-video-details"

const UPDATE_VIDEO_STATUS = BASE_URL + "admin-videos/update-status?"
const PUBLISH_VIDEO = BASE_URL + "admin-videos/publish-video"
const FETCH_PUBLISH_VIDEO = BASE_URL + "published-videos"
const FETCH_UNPUBLISH_VIDEO = BASE_URL + "unpublished-videos"
const UNPUBLISH_VIDEO = BASE_URL + "published-videos/unpublish-videos"

export const ENDPOINTS = {
    ADMIN_USER_LOGIN:ADMIN_USER_LOGIN,
    USERNAME:USERNAME,
    GET_ALL_VIDEO_CATEGORY:GET_ALL_VIDEO_CATEGORY,
    ADD_VIDEO_CATEGORY:ADD_VIDEO_CATEGORY,
    DELETE_VIDEO_CATEGORY:DELETE_VIDEO_CATEGORY,
    UPDATE_VIDEO_CATEGORY:UPDATE_VIDEO_CATEGORY,
    USER_BY_ID:USER_BY_ID,
    GET_ALL_ADMIN_USERS:GET_ALL_ADMIN_USERS,
    CREATE_ADMIN_USER:CREATE_ADMIN_USER,
    UPDATE_ADMIN_USER:UPDATE_ADMIN_USER,
    DELETE_ADMIN_USER:DELETE_ADMIN_USER,
    GET_ALL_VIDEOS_BY_ADMIN:GET_ALL_VIDEOS_BY_ADMIN,
    UPLOAD_VIDEO:UPLOAD_VIDEO,
    DELETE_VIDEO:DELETE_VIDEO,
    UPLOAD_WALLPAPER:UPLOAD_WALLPAPER,
    GET_ALL_WALLPAPER:GET_ALL_WALLPAPER,
    ACTIVE_WALLPAPER:ACTIVE_WALLPAPER,
    ACTIVE_VIDEOS:ACTIVE_VIDEOS,
    UPDATE_VIDEO_STATUS:UPDATE_VIDEO_STATUS,
    FETCH_VERIFY_VIDEOS:FETCH_VERIFY_VIDEOS,
    PUBLISH_VIDEO:PUBLISH_VIDEO,
    FETCH_PUBLISH_VIDEO:FETCH_PUBLISH_VIDEO,
    UNPUBLISH_VIDEO:UNPUBLISH_VIDEO,
    FETCH_UNPUBLISH_VIDEO:FETCH_UNPUBLISH_VIDEO,
    UNVERIFY_VIDEO:UNVERIFY_VIDEO,
    REJECT_PUBLISH_VIDEO:REJECT_PUBLISH_VIDEO,
    FETCH_VERIFICATION_FAILED:FETCH_VERIFICATION_FAILED,
    FETCH_PUBLISH_VIDEO_DETAILS:FETCH_PUBLISH_VIDEO_DETAILS,
    FETCH_VIDEO_BY_ADMIN_DETAILS:FETCH_VIDEO_BY_ADMIN_DETAILS,
    FETCH_VERIFY_VIDEO_DETAILS:FETCH_VERIFY_VIDEO_DETAILS

}
 